import dotenv from 'dotenv'
import path from 'path'
import { googleCalendarService } from './google-calendar.service'

// Load environment variables from apps/server/.env
dotenv.config({ path: path.resolve(__dirname, '../.env') })
dotenv.config()

// Pass KEEP_EVENT=true environment variable or flag to preserve the test event on calendar
const KEEP_EVENT = process.env.KEEP_EVENT === 'true'

async function debugCalendarService() {
   console.log('----------------------------------------------------')
   console.log('📅 Debugging Google Calendar Service')
   console.log('----------------------------------------------------')
   console.log(
      `ℹ️ Mode: ${process.env.GOOGLE_CLIENT_EMAIL ? 'Attempting Real Google Calendar API' : 'Local Mock Calendar'}\n`,
   )

   const todayStr = new Date().toISOString().slice(0, 10)
   const tomorrowStr = new Date(Date.now() + 86400000).toISOString().slice(0, 10)

   // 1. Fetch busy slots for today
   console.log(`1️⃣ [getBusySlots] Fetching busy slots for today (${todayStr})...`)
   try {
      const busySlotsToday = await googleCalendarService.getBusySlots(todayStr)
      console.log(`   Found ${busySlotsToday.length} busy slot(s) for today:`)
      console.dir(busySlotsToday, { depth: null })
   } catch (err) {
      console.error('   ❌ Error fetching busy slots for today:', err)
   }
   console.log('')

   // 2. Fetch busy slots for tomorrow with doctor filter
   console.log(`2️⃣ [getBusySlots] Fetching busy slots for tomorrow (${tomorrowStr}) for "Dr. Patel"...`)
   try {
      const busySlotsPatel = await googleCalendarService.getBusySlots(tomorrowStr, 'Dr. Patel')
      console.log(`   Found ${busySlotsPatel.length} busy slot(s) for Dr. Patel:`)
      console.dir(busySlotsPatel, { depth: null })
   } catch (err) {
      console.error('   ❌ Error fetching busy slots for Dr. Patel:', err)
   }
   console.log('')

   // 3. Create a test event
   console.log('3️⃣ [createEvent] Creating a new test calendar event...')
   let createdEventId: string | null = null
   const startIso = `${tomorrowStr}T11:00:00Z`
   const endIso = `${tomorrowStr}T11:30:00Z`

   try {
      const created = await googleCalendarService.createEvent({
         summary: 'DEBUG: Test Doctor Appointment',
         description: 'Test event generated by debug-calendar script',
         startIso,
         endIso,
         patientEmail: 'test.patient@example.com',
      })
      createdEventId = created.id
      console.log(`   ✅ Event created successfully!`)
      console.log(`   ID: ${created.id}`)
      if (created.htmlLink) {
         console.log(`   Link: ${created.htmlLink}`)
      }
   } catch (err) {
      console.error('   ❌ Error creating event:', err)
   }
   console.log('')
   // console.log("createdEventId", createdEventId); return;
   if (createdEventId) {
      // 4. Retrieve event details
      console.log(`4️⃣ [getEvent] Fetching details for event ID: ${createdEventId}...`)
      try {
         const eventDetails = await googleCalendarService.getEvent(createdEventId)
         console.log('   Event Details:')
         console.dir(eventDetails, { depth: null })
      } catch (err) {
         console.error('   ❌ Error getting event details:', err)
      }
      console.log('')

      // 5. Update event
      console.log(`5️⃣ [updateEvent] Rescheduling event to 12:00 PM...`)
      const updatedStartIso = `${tomorrowStr}T12:00:00Z`
      const updatedEndIso = `${tomorrowStr}T12:30:00Z`
      try {
         const updated = await googleCalendarService.updateEvent(createdEventId, {
            summary: 'DEBUG: Rescheduled Doctor Appointment',
            description: 'Test event updated by debug-calendar script',
            startIso: updatedStartIso,
            endIso: updatedEndIso,
         })
         console.log(`   ✅ Event updated successfully! ID: ${updated.id}`)

         const updatedDetails = await googleCalendarService.getEvent(createdEventId)
         console.log('   Updated Details:', updatedDetails)
      } catch (err) {
         console.error('   ❌ Error updating event:', err)
      }
      console.log('')

      // 6. Delete event
      if (!KEEP_EVENT) {
         console.log(`6️⃣ [deleteEvent] Cleaning up and deleting event ID: ${createdEventId}...`)
         try {
            const deleted = await googleCalendarService.deleteEvent(createdEventId)
            console.log(`   ✅ Event deleted status: ${deleted}`)
         } catch (err) {
            console.error('   ❌ Error deleting event:', err)
         }
      } else {
         console.log(`6️⃣ [deleteEvent] Skipping deletion (KEEP_EVENT=true).`)
         console.log(`   📌 Event preserved with ID: ${createdEventId}`)
      }
      console.log('')
   }

   console.log('----------------------------------------------------')
   console.log('🎉 Calendar Service Debug Run Completed!')
   console.log('----------------------------------------------------\n')
}

debugCalendarService().catch((err) => {
   console.error('Fatal error during calendar debug run:', err)
})
