services:
  app:
    image: bhavin42/ai-demo:latest
    ports:
      - "3001:3001"
      - "5173:5173"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: unless-stopped

volumes:
  mongo_data:
